title: "Artheral"
description: "Web dev • Freelancer • business enthusiast • Graphics designer"
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: false
google_analytics: true
